name: Build Multi-OS
on: [push, pull_request]

permissions:
  contents: write
jobs:
        
  mvn-build:
    name: mvn-build-${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:

        name: [
          windows,
          mac,
          linux,
          linux-all-natives
        ]

        include:
          - name: windows
            os: windows-latest
            extra-build-args: ""
          - name: mac
            os: macos-latest
            extra-build-args: ""
          - name: linux
            os: ubuntu-latest
            extra-build-args: ""
          - name: linux-all-natives
            os: ubuntu-latest
            extra-build-args: "-Djblosc.native.include_all"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'

      - name: Maven log os.name
        run: mvn help:evaluate -Dexpression="os.name"

      - name: Maven log os.arch
        run: mvn help:evaluate -Dexpression="os.arch"

      - name: Maven display-info
        run: mvn enforcer:display-info

      - name: Maven build and test
        run: mvn ${{ matrix.extra-build-args || '.not-used' }} package test

      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          append_body: true
          files: "target/jblosc-native*.jar"

      # TODO:
      # - name: Set up CI environment
      #   run: .github/setup.sh
      # - name: Execute the build
      #   run: .github/build.sh
