name: CI CMake
on: [push, pull_request]
jobs:
  native:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [
          windows,
          mac
        ]
        include:

          - name: windows
            os: windows-2019
            compiler: cl
            cmake-args: -A x64
            lib-extension: dll

          - name: mac
            os: macos-11
            compiler: gcc
            lib-extension: dylib

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Install packages (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install ninja ${{ matrix.packages }}

    - name: Install packages (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install ninja ${{ matrix.packages }}

    - name: Generate project files
      run: |
        cd 'c-blosc'
        cmake '.' ${{ matrix.cmake-args }} -DCMAKE_BUILD_TYPE=${{ matrix.build-config || 'Release' }} -DBUILD_FUZZERS=ON
      env:
        CC: ${{ matrix.compiler }}
        CFLAGS: ${{ matrix.cflags }}
        LDFLAGS: ${{ matrix.ldflags }}
        CI: true

    - name: Compile source code
      run: |
        cd 'c-blosc'
        cmake --build . --config ${{ matrix.build-config || 'Release' }}
    - name: List contents
      run: |
        ls 'c-blosc/blosc'
    - uses: actions/upload-artifact@master
      with:
        name: libblosc.${{ matrix.lib-extension }}
        path: c-blosc/blosc/libblosc.${{ matrix.lib-extension }}
        
  mvn-build:
    runs-on: ubuntu-latest
    needs: [native]
    steps:
      - uses: actions/checkout@v3

      - name: Make resources dir
        run: |
          mkdir -p src/main/resources

      - uses: actions/download-artifact@master
        with:
          name: libblosc.dylib
          path: src/main/resources/natives//osx_64/libblosc.dylib

      - uses: actions/download-artifact@master
        with:
          name: libblosc.dll
          path: src/main/resources/natives//windows_64/libblosc.dll

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'
      - name: Set up CI environment
        run: .github/setup.sh
      - name: Execute the build
        run: .github/build.sh
