name: CI CMake
on: [push, pull_request]
jobs:
  ci-cmake:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [
          Ubuntu GCC,
          Windows MSVC Win64,
          macOS GCC
        ]
        include:
          - name: Ubuntu GCC
            os: ubuntu-20.04
            compiler: gcc
            lib-extension: so

          - name: Windows MSVC Win64
            os: windows-2019
            compiler: cl
            cmake-args: -A x64
            lib-extension: dll

          - name: macOS GCC
            os: macos-11
            compiler: gcc
            lib-extension: dylib

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Install packages (Ubuntu)
      if: runner.os == 'Linux' && matrix.packages
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.packages }}

    - name: Install packages (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install ninja ${{ matrix.packages }}

    - name: Install packages (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install ninja ${{ matrix.packages }}

    - name: Generate project files
      run: |
        cd 'c-blosc'
        cmake '.' ${{ matrix.cmake-args }} -DCMAKE_BUILD_TYPE=${{ matrix.build-config || 'Release' }} -DBUILD_FUZZERS=ON
      env:
        CC: ${{ matrix.compiler }}
        CFLAGS: ${{ matrix.cflags }}
        LDFLAGS: ${{ matrix.ldflags }}
        CI: true

    - name: Compile source code
      run: |
        cd 'c-blosc'
        cmake --build . --config ${{ matrix.build-config || 'Release' }}
    - uses: actions/upload-artifact@master
      with:
        name: libblosc.${{ matrix.lib-extension }}
        path: blosc/libblosc.${{ matrix.lib-extension }}
        
  mvn-build:
    runs-on: ubuntu-latest
    steps:
      - name: Make resources dir
        run: |
          mkdir -p src/main/resources

      - uses: actions/download-artifact@master
        with:
          name: libblosc.so
          path: src/main/resources/libblosc.so

      - uses: actions/download-artifact@master
        with:
          name: libblosc.dylib
          path: src/main/resources/libblosc.dylib

      - uses: actions/download-artifact@master
        with:
          name: libblosc.dll
          path: src/main/resources/libblosc.dll

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'
      - name: Set up CI environment
        run: .github/setup.sh
      - name: Execute the build
        run: .github/build.sh

      # n otests for now but uncomment once this is more stable
      # - name: Run test cases
      #   run: |
      #     cd ${{ matrix.build-dir || 'c-blosc' }}
      #     ctest -C Release --output-on-failure --max-width 120
